version: '3'


services:


  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: demoDB
    ports:
      - '5430:5432'
